"""
企业级多法人实体内部交易对账与合并报表自动化系统
"""
GROUP_NAME = "集团总部"
DB_URL = "sqlite:///consolidation.db"
WORK_ORDER_TIMEOUT_HOURS = 48
REPORT_SUBMISSION_DELAY_DAYS = 2
MANUAL_ADJUSTMENT_THRESHOLD = 5_000_000
CONCURRENT_WORKERS = 8
BATCH_SIZE = 1000
DIFFERENCE_TOLERANCE = 0.01

ESCALATION_LEVELS = {
    1: "子公司CFO",
    2: "集团财务总监",
    3: "CEO",
}

APPROVAL_FLOW = ["子公司CFO", "集团财务总监", "CEO"]

NOTIFICATION_WEBHOOK_URL = ""
NOTIFICATION_ENABLED = True

LOG_FILE = "logs/operations.log"
LOG_MAX_BYTES = 50 * 1024 * 1024
LOG_BACKUP_COUNT = 10

QUARTERLY_REPORT_MONTHS = [3, 6, 9, 12]
